# Generated by Django 2.2.6 on 2019-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('money', models.IntegerField(default=1000)),
                ('item_1_amount', models.IntegerField(default=0)),
                ('item_2_amount', models.IntegerField(default=0)),
                ('item_3_amount', models.IntegerField(default=0)),
                ('item_4_amount', models.IntegerField(default=0)),
                ('item_5_amount', models.IntegerField(default=0)),
                ('item_6_amount', models.IntegerField(default=0)),
                ('loan', models.IntegerField(default=0)),
            ],
        ),
    ]
