# Generated by Django 2.2.6 on 2019-10-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0002_auto_20191015_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='loan',
            new_name='debt',
        ),
    ]
