# Generated by Django 2.2.6 on 2019-10-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0003_auto_20191015_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='item_1_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_2_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_3_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_4_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_5_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='item_6_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='CityStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('item_1_buy_price', models.IntegerField(blank=True)),
                ('item_1_sell_price', models.IntegerField(blank=True)),
                ('item_2_buy_price', models.IntegerField(blank=True)),
                ('item_2_sell_price', models.IntegerField(blank=True)),
                ('item_3_buy_price', models.IntegerField(blank=True)),
                ('item_3_sell_price', models.IntegerField(blank=True)),
                ('item_4_buy_price', models.IntegerField(blank=True)),
                ('item_4_sell_price', models.IntegerField(blank=True)),
                ('item_5_buy_price', models.IntegerField(blank=True)),
                ('item_5_sell_price', models.IntegerField(blank=True)),
                ('item_6_buy_price', models.IntegerField(blank=True)),
                ('item_6_sell_price', models.IntegerField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.City')),
            ],
        ),
    ]
