# Generated by Django 2.2.6 on 2019-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0004_auto_20191015_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystock',
            name='item_1_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_1_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_2_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_2_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_3_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_3_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_4_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_4_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_5_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_5_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_6_buy_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citystock',
            name='item_6_sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
