# Generated by Django 2.2.6 on 2019-10-16 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0006_gamedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 20, 32, 42, 442396, tzinfo=utc)),
        ),
    ]
