# Generated by Django 2.2.6 on 2019-10-17 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0007_auto_20191016_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='debt',
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 14, 7, 33, 657281, tzinfo=utc)),
        ),
    ]
