# Generated by Django 2.2.6 on 2019-10-17 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0008_auto_20191017_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='starting_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 14, 36, 20, 516788, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Player')),
            ],
        ),
    ]
