# Generated by Django 3.0.3 on 2020-02-28 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0009_auto_20191017_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='starting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
