# Generated by Django 3.0.3 on 2020-02-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0010_auto_20200228_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('number', models.IntegerField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
