# Generated by Django 3.0.3 on 2020-02-28 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0011_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystock',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Round'),
        ),
    ]
