# Generated by Django 3.0.6 on 2020-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0012_auto_20200228_1854'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citystock',
            constraint=models.UniqueConstraint(fields=('city', 'round'), name='city_stock'),
        ),
    ]
