# Generated by Django 3.0.6 on 2020-05-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0013_auto_20200510_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='item_1_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='item_2_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='item_3_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='item_4_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='item_5_amount',
        ),
        migrations.RemoveField(
            model_name='player',
            name='item_6_amount',
        ),
        migrations.CreateModel(
            name='ItemExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.IntegerField(blank=True, null=True)),
                ('sell_price', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.City')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Item')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Round')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemexchangerate',
            constraint=models.UniqueConstraint(fields=('item', 'city', 'round'), name='city_item_exchange'),
        ),
        migrations.AddConstraint(
            model_name='itemamount',
            constraint=models.UniqueConstraint(fields=('item', 'player'), name='player_item'),
        ),
    ]
