# Generated by Django 3.0.6 on 2020-05-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0014_auto_20200513_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CityStock',
        ),
    ]
