# Generated by Django 3.0.6 on 2020-05-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0015_auto_20200519_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='round_duration',
            field=models.IntegerField(default=15, verbose_name='Round duration in minutes'),
        ),
        migrations.AlterField(
            model_name='itemamount',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='merchant_game.Player'),
        ),
        migrations.AlterField(
            model_name='itemexchangerate',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='merchant_game.City'),
        ),
    ]
