# Generated by Django 3.0.6 on 2020-05-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0016_auto_20200523_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='active_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merchant_game.Round'),
            preserve_default=False,
        ),
    ]
