# Generated by Django 3.0.6 on 2020-06-04 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0018_remove_gamedata_active_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemamount',
            name='amount',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
