# Generated by Django 3.0.6 on 2020-06-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0019_auto_20200605_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='loan_increase',
            field=models.IntegerField(default=100, verbose_name='Loan increase in each round'),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='starting_loan',
            field=models.IntegerField(default=500, verbose_name='Loan in the first round'),
        ),
    ]
