# Generated by Django 3.0.6 on 2020-06-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0020_auto_20200605_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='merchant_game.Player'),
        ),
    ]
