# Generated by Django 3.0.6 on 2020-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0022_auto_20200605_2237'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='player_loan_round'),
        ),
    ]
