# Generated by Django 3.0.6 on 2020-06-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0024_remove_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='loan_interest',
            field=models.IntegerField(default=10, verbose_name='Loan interest rate (%)'),
        ),
    ]
