# Generated by Django 3.0.6 on 2020-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0025_gamedata_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ending_price',
            field=models.IntegerField(default=10),
        ),
    ]
