# Generated by Django 3.0.6 on 2020-06-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_game', '0027_auto_20200609_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertransaction',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taking_transactions', to='merchant_game.Player'),
        ),
    ]
